#!/bin/bash -e

rm -f /etc/cni/net.d/10-kuryr.conf
rm -f /etc/cni/net.d/99-loopback.conf
rm -f /opt/cni/bin/kuryr-cni
rm -f /opt/cni/bin/kuryr-cni-bin
rm -rf /etc/kuryr
mkdir /etc/kuryr
cp /var/run/secrets/kubernetes.io/serviceaccount/token /etc/kuryr/token
cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /etc/kuryr/ca.crt
cp /opt/kuryr-kubernetes/etc/cni/net.d/* /etc/cni/net.d/
cp /kuryr-cni-bin /opt/cni/bin/kuryr-cni-bin
cp /kuryr-cni /opt/cni/bin/kuryr-cni
cat /tmp/kuryr/* > /etc/kuryr/kuryr.conf

while true; do sleep 3600; done
