#!/bin/bash -ex

CNI_BIN_DIR=$1
CNI_CONF_DIR=$2
CNI_DAEMON=${3:-"False"}
CNI_TAG="kuryr/cni"

# create cni daemonset image
docker build -t "$CNI_TAG" \
    --build-arg "CNI_BIN_DIR_PATH=$CNI_BIN_DIR" \
    --build-arg "CNI_CONFIG_DIR_PATH=$CNI_CONF_DIR" \
    --build-arg "CNI_DAEMON=$CNI_DAEMON" \
    -f cni.Dockerfile .
